import assert from 'node:assert/strict';
import { movePlace, validBoard, selectPuzzle, nextPuzzleCountdown, restoreProgress, shareText, advanceSolveTimer, formatSolveTime, restoreHintedPlaces } from '../public/state.mjs';

const ids = ['bakery','cafe','books','florist','park','pond','homes','bikes','market'];
const empty = Array(9).fill(null);
assert.equal(validBoard(empty, ids), true);
assert.equal(validBoard(['bakery','bakery',...Array(7).fill(null)], ids), false);
assert.equal(validBoard([...Array(8).fill(null),'<script>'], ids), false);
const placed = movePlace(empty, 'bakery', 0);
assert.deepEqual(placed, ['bakery',...Array(8).fill(null)]);
assert.deepEqual(empty, Array(9).fill(null));
assert.deepEqual(movePlace(['bakery','cafe',...Array(7).fill(null)], 'bakery', 1), ['cafe','bakery',...Array(7).fill(null)]);
assert.deepEqual(movePlace(['bakery',...Array(8).fill(null)], 'cafe', 0), ['cafe',...Array(8).fill(null)]);
assert.deepEqual(movePlace(placed, 'bakery', null), empty);
assert.throws(() => movePlace(empty, 'bakery', 9), RangeError);

const bank = {tutorial:{date:'tutorial'},puzzles:[{date:'2026-09-10'},{date:'2026-09-11'}]};
assert.deepEqual(selectPuzzle(bank,'2026-09-10'),{puzzle:bank.puzzles[0],mode:'daily'});
assert.deepEqual(selectPuzzle(bank,'2026-09-10','2026-09-11'),{puzzle:bank.puzzles[0],mode:'daily'});
assert.deepEqual(selectPuzzle(bank,'2026-09-11','2026-09-10'),{puzzle:bank.puzzles[0],mode:'archive'});
assert.deepEqual(selectPuzzle(bank,'2027-01-01'),{puzzle:bank.tutorial,mode:'practice'});
assert.deepEqual(selectPuzzle(bank,'2026-09-10','practice'),{puzzle:bank.tutorial,mode:'practice'});
assert.equal(nextPuzzleCountdown(new Date('2026-09-12T23:59:59.999Z')),'00:00:01');
assert.equal(nextPuzzleCountdown(new Date('2026-09-13T00:00:00Z')),'24:00:00');
assert.equal(nextPuzzleCountdown(new Date('2026-09-12T19:30:00-04:00')),'00:30:00');
assert.equal(nextPuzzleCountdown(new Date('2026-09-30T23:00:00Z')),'01:00:00');
assert.equal(nextPuzzleCountdown(new Date('2026-12-31T23:59:58.500Z')),'00:00:02');
assert.deepEqual(restoreProgress('{bad',ids),{board:empty,moves:0,hints:0,hintedPlaces:[],reported:false,elapsedMs:0});
assert.deepEqual(restoreProgress(JSON.stringify({board:placed,moves:5,hints:2,reported:true}),ids),{board:placed,moves:5,hints:2,hintedPlaces:[],reported:true,elapsedMs:null});
assert.equal(restoreProgress(JSON.stringify({board:placed,moves:-1,hints:'2'}),ids).moves,0);
assert.equal(restoreProgress(JSON.stringify({board:['injected'],reported:true}),ids).reported,false);
assert.equal(restoreProgress(JSON.stringify({board:placed,elapsedMs:1234}),ids).elapsedMs,1234);
assert.equal(restoreProgress(JSON.stringify({board:empty,elapsedMs:1234}),ids).elapsedMs,0);
assert.equal(restoreProgress(JSON.stringify({board:placed,elapsedMs:-1}),ids).elapsedMs,null);
const restoredHints = restoreProgress(JSON.stringify({board:movePlace(placed,'cafe',2),hints:1,hintedPlaces:['cafe','cafe','unknown',null],elapsedMs:500}),ids,ids);
assert.deepEqual(restoredHints.hintedPlaces,['cafe']);
assert.deepEqual(restoredHints.board,['bakery','cafe',...Array(7).fill(null)]);
assert.equal(restoredHints.hints,1);
assert.deepEqual(restoreHintedPlaces(empty,['bakery','cafe'],ids),['bakery','cafe',...Array(7).fill(null)]);
assert.deepEqual(restoreHintedPlaces(movePlace(empty,'books',0),['bakery'],ids),placed);
assert.deepEqual(restoreProgress(JSON.stringify({board:placed,hints:3}),ids,ids).hintedPlaces,[]);
assert.equal(restoreProgress(JSON.stringify({board:placed,hints:3}),ids,ids).hints,3);
assert.equal(restoreProgress(JSON.stringify({board:placed,hints:0,hintedPlaces:['bakery','cafe']}),ids,ids).hints,2);
assert.deepEqual(restoreProgress(JSON.stringify({board:placed,hintedPlaces:'bakery'}),ids,ids).hintedPlaces,[]);
assert.deepEqual(restoreProgress(JSON.stringify({board:placed,hintedPlaces:['bakery']}),ids,empty).hintedPlaces,[]);
let timer = {elapsedMs:0,startedAt:null};
timer = advanceSolveTimer(timer,1000,false,false);
assert.deepEqual(timer,{elapsedMs:0,startedAt:null});
timer = advanceSolveTimer(timer,5000,true,true);
assert.deepEqual(timer,{elapsedMs:0,startedAt:5000});
timer = advanceSolveTimer(timer,7000,true,false);
assert.deepEqual(timer,{elapsedMs:2000,startedAt:null});
timer = advanceSolveTimer(timer,17000,true,true);
timer = advanceSolveTimer(timer,18000,true,false);
assert.deepEqual(timer,{elapsedMs:3000,startedAt:null});
timer = advanceSolveTimer(timer,30000,true,false);
assert.equal(timer.elapsedMs,3000);
timer = advanceSolveTimer(timer,40000,false,false);
assert.deepEqual(timer,{elapsedMs:0,startedAt:null});
assert.deepEqual(advanceSolveTimer(timer,45000,true,false),{elapsedMs:0,startedAt:null});
timer = advanceSolveTimer(timer,50000,true,true);
timer = advanceSolveTimer(timer,51000,false,true);
assert.deepEqual(timer,{elapsedMs:0,startedAt:null});
assert.deepEqual(advanceSolveTimer({elapsedMs:null,startedAt:null},1000,true,true),{elapsedMs:null,startedAt:null});
assert.deepEqual(advanceSolveTimer({elapsedMs:null,startedAt:null},1000,false,false),{elapsedMs:0,startedAt:null});
assert.equal(formatSolveTime(61000),'1:01');
assert.equal(formatSolveTime(3661000),'1:01:01');
assert.equal(formatSolveTime(100),'0:01');
assert.equal(formatSolveTime(0),'');
assert.equal(formatSolveTime(null),'');
assert.equal(shareText('2026-09-10',0,'https://example.com/'), 'NookGrid · September 10, 2026\n🏡 A little neighborhood, all in place.\nSolved without hints.\nhttps://example.com/?date=2026-09-10&utm_source=share&utm_medium=result&utm_campaign=daily&utm_content=result_card');
console.log('State checks passed: placement, swaps, validation, dates, UTC countdown, persistence, spoiler-free sharing.');
